import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Link from "../../node_modules/next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React Master",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen max-w-7xl m-auto">
          <nav className="border-r-2 px-4 py-8 flex flex-col gap-2 items-start whitespace-nowrap">
            <Link href="/">Home</Link>
            <h3>Basic</h3>
            <Link href="/studies/basic/layout">Layout</Link>
            <Link href="/studies/basic/fetch">Fetch</Link>
            <h3>React Hooks</h3>
            <Link href="/studies/hooks/useState">UseState</Link>
            <Link href="/studies/hooks/useEffect">UseEffect</Link>
          </nav>
          {/* <main>
            <div className="demo"> {children}</div>
            <div className="markdown"></div>
          </main> */}
          {children}
        </div>
      </body>
    </html>
  );
}
